version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  flask:
    build: ./backend/flask
    ports:
      - "8000:5000"
    depends_on:
      - redis

  fastapi:
    build: ./backend/fastapi
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - mysql

  node:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

volumes:
  pgdata:
  mysqldata:
